# Search
search:
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: Neko
    url: https://neko.ayaka.moe
  - name: 云羽的羽毛
    url: https://oao.moe

# navigation menu
menu:
  - name: 日记本
    slug: meow
    url: /
  - name: 故事们
    slug: stories
    url: /stories
  - name: 呐？
    slug: about
    url: /nyan

# Since year
since: 2016

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/nekomeowww
- slug: twitter
  url: https://twitter.com/ayakaneko
- slug: rss
  url: /atom.xml
